import "./globals.css";
import { Assistant } from 'next/font/google'

const assistantFont = Assistant({
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
  display: 'swap'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Yahan humne type define kar di hai
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${assistantFont.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}